# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.AuthGetUserRandomCodeParser do
  @moduledoc """
  Parser for auth.get_user_random_code stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.AuthGetUserRandomCodeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserRandomCodeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_user_random_code returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([get_user_random_code]) do
    {:ok, %AuthGetUserRandomCodeModel{
      get_user_random_code: get_user_random_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_random_code result")
    {:error, :invalid_row}
  end
end