# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.CheckVersionParser do
  @moduledoc """
  Parser for public.check_version stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.CheckVersionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CheckVersionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure check_version returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([check_version]) do
    {:ok, %CheckVersionModel{
      check_version: check_version,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in check_version result")
    {:error, :invalid_row}
  end
end