# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureSitePageParser do
  @moduledoc """
  Parser for public.ensure_site_page stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureSitePageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureSitePageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_site_page returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([site_page_id, content_sha, deduped]) do
    {:ok, %EnsureSitePageModel{
      site_page_id: site_page_id,
      content_sha: content_sha,
      deduped: deduped,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_site_page result")
    {:error, :invalid_row}
  end
end