# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureSiteParser do
  @moduledoc """
  Parser for public.ensure_site stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureSiteModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureSiteModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_site returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([site_id, code, title, description, home_slug, settings]) do
    {:ok, %EnsureSiteModel{
      site_id: site_id,
      code: code,
      title: title,
      description: description,
      home_slug: home_slug,
      settings: settings,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_site result")
    {:error, :invalid_row}
  end
end