# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureDocSetPackageParser do
  @moduledoc """
  Parser for public.ensure_doc_set_package stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureDocSetPackageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureDocSetPackageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_doc_set_package returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([doc_set_package_id, doc_set_id, ecosystem_code, package_name]) do
    {:ok, %EnsureDocSetPackageModel{
      doc_set_package_id: doc_set_package_id,
      doc_set_id: doc_set_id,
      ecosystem_code: ecosystem_code,
      package_name: package_name,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_doc_set_package result")
    {:error, :invalid_row}
  end
end