# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureDocVariantParser do
  @moduledoc """
  Parser for public.ensure_doc_variant stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureDocVariantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureDocVariantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_doc_variant returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([doc_variant_id, doc_set_id, code]) do
    {:ok, %EnsureDocVariantModel{
      doc_variant_id: doc_variant_id,
      doc_set_id: doc_set_id,
      code: code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_doc_variant result")
    {:error, :invalid_row}
  end
end