# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureDocumentParser do
  @moduledoc """
  Parser for public.ensure_document stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureDocumentModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureDocumentModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_document returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([document_id, content_sha, deduped]) do
    {:ok, %EnsureDocumentModel{
      document_id: document_id,
      content_sha: content_sha,
      deduped: deduped,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_document result")
    {:error, :invalid_row}
  end
end