# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureDocSetParser do
  @moduledoc """
  Parser for public.ensure_doc_set stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureDocSetModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureDocSetModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_doc_set returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([doc_set_id, code, kind_code, title, description, home_slug, settings]) do
    {:ok, %EnsureDocSetModel{
      doc_set_id: doc_set_id,
      code: code,
      kind_code: kind_code,
      title: title,
      description: description,
      home_slug: home_slug,
      settings: settings,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_doc_set result")
    {:error, :invalid_row}
  end
end