# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureContentBlobParser do
  @moduledoc """
  Parser for public.ensure_content_blob stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureContentBlobModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureContentBlobModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_content_blob returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([sha, deduped]) do
    {:ok, %EnsureContentBlobModel{
      sha: sha,
      deduped: deduped,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_content_blob result")
    {:error, :invalid_row}
  end
end