# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.EnsureDocNavParser do
  @moduledoc """
  Parser for public.ensure_doc_nav stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.EnsureDocNavModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [EnsureDocNavModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_doc_nav returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([doc_nav_id, node_path, full_title, has_children]) do
    {:ok, %EnsureDocNavModel{
      doc_nav_id: doc_nav_id,
      node_path: node_path,
      full_title: full_title,
      has_children: has_children,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_doc_nav result")
    {:error, :invalid_row}
  end
end