# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetDefaultVariantParser do
  @moduledoc """
  Parser for public.get_default_variant stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetDefaultVariantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetDefaultVariantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_default_variant returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, title, show_in_path]) do
    {:ok, %GetDefaultVariantModel{
      code: code,
      title: title,
      show_in_path: show_in_path,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_default_variant result")
    {:error, :invalid_row}
  end
end