# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetSiteNavParser do
  @moduledoc """
  Parser for public.get_site_nav stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetSiteNavModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetSiteNavModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_site_nav returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([level, node_path, label, full_title, slug, doc_set_code, url, is_section, has_children]) do
    {:ok, %GetSiteNavModel{
      level: level,
      node_path: node_path,
      label: label,
      full_title: full_title,
      slug: slug,
      doc_set_code: doc_set_code,
      url: url,
      is_section: is_section,
      has_children: has_children,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_site_nav result")
    {:error, :invalid_row}
  end
end