# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetDocumentIndexParser do
  @moduledoc """
  Parser for public.get_document_index stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetDocumentIndexModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetDocumentIndexModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_document_index returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([title, keywords, search_text, lexemes]) do
    {:ok, %GetDocumentIndexModel{
      title: title,
      keywords: keywords,
      search_text: search_text,
      lexemes: lexemes,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_document_index result")
    {:error, :invalid_row}
  end
end