# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetDocSetParser do
  @moduledoc """
  Parser for public.get_doc_set stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetDocSetModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetDocSetModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_doc_set returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, kind_code, title, description, home_slug, settings, ecosystem_code, package_name]) do
    {:ok, %GetDocSetModel{
      code: code,
      kind_code: kind_code,
      title: title,
      description: description,
      home_slug: home_slug,
      settings: settings,
      ecosystem_code: ecosystem_code,
      package_name: package_name,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_doc_set result")
    {:error, :invalid_row}
  end
end