# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetSitePageParser do
  @moduledoc """
  Parser for public.get_site_page stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetSitePageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetSitePageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_site_page returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([slug, title, content, frontmatter]) do
    {:ok, %GetSitePageModel{
      slug: slug,
      title: title,
      content: content,
      frontmatter: frontmatter,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_site_page result")
    {:error, :invalid_row}
  end
end