# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetDocNavParser do
  @moduledoc """
  Parser for public.get_doc_nav stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetDocNavModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetDocNavModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_doc_nav returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([level, node_path, label, full_title, slug, variant_code, is_section, has_children]) do
    {:ok, %GetDocNavModel{
      level: level,
      node_path: node_path,
      label: label,
      full_title: full_title,
      slug: slug,
      variant_code: variant_code,
      is_section: is_section,
      has_children: has_children,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_doc_nav result")
    {:error, :invalid_row}
  end
end