# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.GetSiteParser do
  @moduledoc """
  Parser for public.get_site stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.GetSiteModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetSiteModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_site returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, title, description, home_slug, settings]) do
    {:ok, %GetSiteModel{
      code: code,
      title: title,
      description: description,
      home_slug: home_slug,
      settings: settings,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_site result")
    {:error, :invalid_row}
  end
end