# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.ListDocSetsParser do
  @moduledoc """
  Parser for public.list_doc_sets stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.ListDocSetsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [ListDocSetsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure list_doc_sets returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, kind_code, title, ecosystem_code, package_name]) do
    {:ok, %ListDocSetsModel{
      code: code,
      kind_code: kind_code,
      title: title,
      ecosystem_code: ecosystem_code,
      package_name: package_name,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in list_doc_sets result")
    {:error, :invalid_row}
  end
end