# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.ListDocVariantsParser do
  @moduledoc """
  Parser for public.list_doc_variants stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.ListDocVariantsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [ListDocVariantsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure list_doc_variants returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, title, is_default, show_in_path, maturity_code, applies_to]) do
    {:ok, %ListDocVariantsModel{
      code: code,
      title: title,
      is_default: is_default,
      show_in_path: show_in_path,
      maturity_code: maturity_code,
      applies_to: applies_to,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in list_doc_variants result")
    {:error, :invalid_row}
  end
end