# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.SearchDocumentsParser do
  @moduledoc """
  Parser for public.search_documents stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.SearchDocumentsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [SearchDocumentsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure search_documents returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([doc_set_code, kind_code, variant_code, slug, title, rank, total_count]) do
    {:ok, %SearchDocumentsModel{
      doc_set_code: doc_set_code,
      kind_code: kind_code,
      variant_code: variant_code,
      slug: slug,
      title: title,
      rank: rank,
      total_count: total_count,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_documents result")
    {:error, :invalid_row}
  end
end