# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Parsers.StopVersionUpdateParser do
  @moduledoc """
  Parser for public.stop_version_update stored procedure results.
  """

  require Logger

  alias KeenDocs.Database.Models.StopVersionUpdateModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [StopVersionUpdateModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure stop_version_update returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([version_id, component, version, title, description, execution_started, execution_finished]) do
    {:ok, %StopVersionUpdateModel{
      version_id: version_id,
      component: component,
      version: version,
      title: title,
      description: description,
      execution_started: execution_started,
      execution_finished: execution_finished,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in stop_version_update result")
    {:error, :invalid_row}
  end
end