# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.AuthGetUserRandomCodeModel do
  @moduledoc """
  Model for auth.get_user_random_code stored procedure result.
  """

  @type t() :: %__MODULE__{
    get_user_random_code: String.t()
  }

  @fields [:get_user_random_code]

  @enforce_keys @fields
  defstruct @fields
end