# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.CheckVersionModel do
  @moduledoc """
  Model for public.check_version stored procedure result.
  """

  @type t() :: %__MODULE__{
    check_version: boolean()
  }

  @fields [:check_version]

  @enforce_keys @fields
  defstruct @fields
end