# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureDocNavModel do
  @moduledoc """
  Model for public.ensure_doc_nav stored procedure result.
  """

  @type t() :: %__MODULE__{
    doc_nav_id: integer(),
    node_path: String.t(),
    full_title: String.t(),
    has_children: boolean()
  }

  @fields [:doc_nav_id, :node_path, :full_title, :has_children]

  @enforce_keys @fields
  defstruct @fields
end