# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureDocVariantModel do
  @moduledoc """
  Model for public.ensure_doc_variant stored procedure result.
  """

  @type t() :: %__MODULE__{
    doc_variant_id: integer(),
    doc_set_id: integer(),
    code: String.t()
  }

  @fields [:doc_variant_id, :doc_set_id, :code]

  @enforce_keys @fields
  defstruct @fields
end