# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureSitePageModel do
  @moduledoc """
  Model for public.ensure_site_page stored procedure result.
  """

  @type t() :: %__MODULE__{
    site_page_id: integer(),
    content_sha: String.t(),
    deduped: boolean()
  }

  @fields [:site_page_id, :content_sha, :deduped]

  @enforce_keys @fields
  defstruct @fields
end