# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureDocSetModel do
  @moduledoc """
  Model for public.ensure_doc_set stored procedure result.
  """

  @type t() :: %__MODULE__{
    doc_set_id: integer(),
    code: String.t(),
    kind_code: String.t(),
    title: String.t()
  }

  @fields [:doc_set_id, :code, :kind_code, :title]

  @enforce_keys @fields
  defstruct @fields
end