# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureDocSetPackageModel do
  @moduledoc """
  Model for public.ensure_doc_set_package stored procedure result.
  """

  @type t() :: %__MODULE__{
    doc_set_package_id: integer(),
    doc_set_id: integer(),
    ecosystem_code: String.t(),
    package_name: String.t()
  }

  @fields [:doc_set_package_id, :doc_set_id, :ecosystem_code, :package_name]

  @enforce_keys @fields
  defstruct @fields
end