# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureDocumentModel do
  @moduledoc """
  Model for public.ensure_document stored procedure result.
  """

  @type t() :: %__MODULE__{
    document_id: integer(),
    content_sha: String.t(),
    deduped: boolean()
  }

  @fields [:document_id, :content_sha, :deduped]

  @enforce_keys @fields
  defstruct @fields
end