# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.EnsureContentBlobModel do
  @moduledoc """
  Model for public.ensure_content_blob stored procedure result.
  """

  @type t() :: %__MODULE__{
    sha: String.t(),
    deduped: boolean()
  }

  @fields [:sha, :deduped]

  @enforce_keys @fields
  defstruct @fields
end