# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetDocumentIndexModel do
  @moduledoc """
  Model for public.get_document_index stored procedure result.
  """

  @type t() :: %__MODULE__{
    title: String.t(),
    keywords: String.t(),
    search_text: String.t(),
    lexemes: String.t()
  }

  @fields [:title, :keywords, :search_text, :lexemes]

  @enforce_keys @fields
  defstruct @fields
end