# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetSiteModel do
  @moduledoc """
  Model for public.get_site stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    description: String.t(),
    home_slug: String.t(),
    settings: map() | list()
  }

  @fields [:code, :title, :description, :home_slug, :settings]

  @enforce_keys @fields
  defstruct @fields
end