# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetDocSetModel do
  @moduledoc """
  Model for public.get_doc_set stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    kind_code: String.t(),
    title: String.t(),
    description: String.t(),
    home_slug: String.t(),
    settings: map() | list(),
    ecosystem_code: String.t(),
    package_name: String.t()
  }

  @fields [:code, :kind_code, :title, :description, :home_slug, :settings, :ecosystem_code, :package_name]

  @enforce_keys @fields
  defstruct @fields
end