# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetDocumentModel do
  @moduledoc """
  Model for public.get_document stored procedure result.
  """

  @type t() :: %__MODULE__{
    slug: String.t(),
    title: String.t(),
    content: String.t(),
    frontmatter: map() | list()
  }

  @fields [:slug, :title, :content, :frontmatter]

  @enforce_keys @fields
  defstruct @fields
end