# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetDefaultVariantModel do
  @moduledoc """
  Model for public.get_default_variant stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    show_in_path: boolean()
  }

  @fields [:code, :title, :show_in_path]

  @enforce_keys @fields
  defstruct @fields
end