# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetDocNavModel do
  @moduledoc """
  Model for public.get_doc_nav stored procedure result.
  """

  @type t() :: %__MODULE__{
    level: integer(),
    node_path: String.t(),
    label: String.t(),
    full_title: String.t(),
    slug: String.t(),
    variant_code: String.t(),
    is_section: boolean(),
    has_children: boolean()
  }

  @fields [:level, :node_path, :label, :full_title, :slug, :variant_code, :is_section, :has_children]

  @enforce_keys @fields
  defstruct @fields
end