# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.GetSiteNavModel do
  @moduledoc """
  Model for public.get_site_nav stored procedure result.
  """

  @type t() :: %__MODULE__{
    level: integer(),
    node_path: String.t(),
    label: String.t(),
    full_title: String.t(),
    slug: String.t(),
    doc_set_code: String.t(),
    url: String.t(),
    is_section: boolean(),
    has_children: boolean()
  }

  @fields [:level, :node_path, :label, :full_title, :slug, :doc_set_code, :url, :is_section, :has_children]

  @enforce_keys @fields
  defstruct @fields
end