# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.ListDocVariantsModel do
  @moduledoc """
  Model for public.list_doc_variants stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    is_default: boolean(),
    show_in_path: boolean(),
    maturity_code: String.t(),
    applies_to: map() | list()
  }

  @fields [:code, :title, :is_default, :show_in_path, :maturity_code, :applies_to]

  @enforce_keys @fields
  defstruct @fields
end