# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.ListDocSetsModel do
  @moduledoc """
  Model for public.list_doc_sets stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    kind_code: String.t(),
    title: String.t(),
    description: String.t(),
    ecosystem_code: String.t(),
    package_name: String.t()
  }

  @fields [:code, :kind_code, :title, :description, :ecosystem_code, :package_name]

  @enforce_keys @fields
  defstruct @fields
end