# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.ResolveDocVariantModel do
  @moduledoc """
  Model for public.resolve_doc_variant stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    show_in_path: boolean(),
    matched: boolean()
  }

  @fields [:code, :title, :show_in_path, :matched]

  @enforce_keys @fields
  defstruct @fields
end