# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.SearchDocumentsModel do
  @moduledoc """
  Model for public.search_documents stored procedure result.
  """

  @type t() :: %__MODULE__{
    doc_set_code: String.t(),
    kind_code: String.t(),
    variant_code: String.t(),
    slug: String.t(),
    title: String.t(),
    rank: float(),
    total_count: integer()
  }

  @fields [:doc_set_code, :kind_code, :variant_code, :slug, :title, :rank, :total_count]

  @enforce_keys @fields
  defstruct @fields
end