# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database.Models.StopVersionUpdateModel do
  @moduledoc """
  Model for public.stop_version_update stored procedure result.
  """

  @type t() :: %__MODULE__{
    version_id: integer(),
    component: String.t(),
    version: String.t(),
    title: String.t(),
    description: String.t() | nil,
    execution_started: DateTime.t(),
    execution_finished: DateTime.t() | nil
  }

  @fields [:version_id, :component, :version, :title, :description, :execution_started, :execution_finished]

  @enforce_keys @fields
  defstruct @fields
end