# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenDocs.Database do
  @moduledoc """
  Database context module providing wrapper functions for auth stored procedures.
  This code has been auto-generated - changes to this file will be lost on next generation.

  ## Usage

      defmodule MyApp.Database do
        use KeenDocs.Database, repo: MyApp.Repo
      end
  """

  defmacro __using__(opts) do
    quote do
      require Logger

      import unquote(opts[:repo]), only: [query: 2]

      alias KeenDocs.Database.Models
      alias KeenDocs.Database.Parsers


      @doc """
      Calls database function public.check_version
      """
      @spec check_version(String.t(), String.t()) ::
              {:ok, [Models.CheckVersionModel.t()]} | {:error, any()}
      def check_version(version, component) do
        Logger.debug("Calling stored procedure", procedure: "check_version")

        query(
          "select * from public.check_version($1, $2)",
          [version, component]
        )
        |> Parsers.CheckVersionParser.parse_result()
      end


      @doc """
      Calls database function public.ensure_content_blob
      """
      @spec ensure_content_blob(String.t(), String.t(), binary(), integer()) ::
              {:ok, [Models.EnsureContentBlobModel.t()]} | {:error, any()}
      def ensure_content_blob(created_by, sha, content, byte_size) do
        Logger.debug("Calling stored procedure", procedure: "ensure_content_blob")

        query(
          "select * from public.ensure_content_blob($1, $2, $3, $4)",
          [created_by, sha, content, byte_size]
        )
        |> Parsers.EnsureContentBlobParser.parse_result()
      end


      @doc """
      Calls database function public.ensure_doc_set
      """
      @spec ensure_doc_set(String.t(), String.t(), String.t(), String.t(), String.t(), integer()) ::
              {:ok, [Models.EnsureDocSetModel.t()]} | {:error, any()}
      def ensure_doc_set(created_by, correlation_id, code, title, kind_code, tenant_id) do
        Logger.debug("Calling stored procedure", procedure: "ensure_doc_set")

        query(
          "select * from public.ensure_doc_set($1, $2, $3, $4, $5, $6)",
          [created_by, correlation_id, code, title, kind_code, tenant_id]
        )
        |> Parsers.EnsureDocSetParser.parse_result()
      end


      @doc """
      Calls database function public.ensure_doc_set_package
      """
      @spec ensure_doc_set_package(String.t(), String.t(), String.t(), String.t(), String.t(), boolean(), integer()) ::
              {:ok, [Models.EnsureDocSetPackageModel.t()]} | {:error, any()}
      def ensure_doc_set_package(created_by, correlation_id, doc_set_code, ecosystem_code, package_name, is_primary, tenant_id) do
        Logger.debug("Calling stored procedure", procedure: "ensure_doc_set_package")

        query(
          "select * from public.ensure_doc_set_package($1, $2, $3, $4, $5, $6, $7)",
          [created_by, correlation_id, doc_set_code, ecosystem_code, package_name, is_primary, tenant_id]
        )
        |> Parsers.EnsureDocSetPackageParser.parse_result()
      end


      @doc """
      Calls database function public.ensure_doc_variant
      """
      @spec ensure_doc_variant(String.t(), String.t(), String.t(), String.t(), String.t(), boolean(), boolean(), integer(), String.t(), map() | list(), String.t(), integer()) ::
              {:ok, [Models.EnsureDocVariantModel.t()]} | {:error, any()}
      def ensure_doc_variant(created_by, correlation_id, doc_set_code, code, title, is_default, show_in_path, sort_order, maturity_code, applies_to, content_sha, tenant_id) do
        Logger.debug("Calling stored procedure", procedure: "ensure_doc_variant")

        query(
          "select * from public.ensure_doc_variant($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)",
          [created_by, correlation_id, doc_set_code, code, title, is_default, show_in_path, sort_order, maturity_code, applies_to, content_sha, tenant_id]
        )
        |> Parsers.EnsureDocVariantParser.parse_result()
      end


      @doc """
      Calls database function public.ensure_document
      """
      @spec ensure_document(String.t(), String.t(), String.t(), String.t(), String.t(), String.t(), String.t(), map() | list(), String.t(), String.t(), integer()) ::
              {:ok, [Models.EnsureDocumentModel.t()]} | {:error, any()}
      def ensure_document(created_by, correlation_id, doc_set_code, variant_code, slug, title, content, frontmatter, content_sha, search_text, tenant_id) do
        Logger.debug("Calling stored procedure", procedure: "ensure_document")

        query(
          "select * from public.ensure_document($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)",
          [created_by, correlation_id, doc_set_code, variant_code, slug, title, content, frontmatter, content_sha, search_text, tenant_id]
        )
        |> Parsers.EnsureDocumentParser.parse_result()
      end


      @doc """
      Calls database function public.get_default_variant
      """
      @spec get_default_variant(String.t()) ::
              {:ok, [Models.GetDefaultVariantModel.t()]} | {:error, any()}
      def get_default_variant(doc_set_code) do
        Logger.debug("Calling stored procedure", procedure: "get_default_variant")

        query(
          "select * from public.get_default_variant($1)",
          [doc_set_code]
        )
        |> Parsers.GetDefaultVariantParser.parse_result()
      end


      @doc """
      Calls database function public.get_document
      """
      @spec get_document(String.t(), String.t(), String.t()) ::
              {:ok, [Models.GetDocumentModel.t()]} | {:error, any()}
      def get_document(doc_set_code, variant_code, slug) do
        Logger.debug("Calling stored procedure", procedure: "get_document")

        query(
          "select * from public.get_document($1, $2, $3)",
          [doc_set_code, variant_code, slug]
        )
        |> Parsers.GetDocumentParser.parse_result()
      end


      @doc """
      Calls database function public.get_document_index
      """
      @spec get_document_index(String.t(), String.t(), String.t()) ::
              {:ok, [Models.GetDocumentIndexModel.t()]} | {:error, any()}
      def get_document_index(doc_set_code, variant_code, slug) do
        Logger.debug("Calling stored procedure", procedure: "get_document_index")

        query(
          "select * from public.get_document_index($1, $2, $3)",
          [doc_set_code, variant_code, slug]
        )
        |> Parsers.GetDocumentIndexParser.parse_result()
      end


      @doc """
      Calls database function public.list_doc_sets
      """
      @spec list_doc_sets() ::
              {:ok, [Models.ListDocSetsModel.t()]} | {:error, any()}
      def list_doc_sets() do
        Logger.debug("Calling stored procedure", procedure: "list_doc_sets")

        query(
          "select * from public.list_doc_sets()",
          []
        )
        |> Parsers.ListDocSetsParser.parse_result()
      end


      @doc """
      Calls database function public.list_doc_variants
      """
      @spec list_doc_variants(String.t()) ::
              {:ok, [Models.ListDocVariantsModel.t()]} | {:error, any()}
      def list_doc_variants(doc_set_code) do
        Logger.debug("Calling stored procedure", procedure: "list_doc_variants")

        query(
          "select * from public.list_doc_variants($1)",
          [doc_set_code]
        )
        |> Parsers.ListDocVariantsParser.parse_result()
      end


      @doc """
      Calls database function public.resolve_doc_variant
      """
      @spec resolve_doc_variant(String.t(), String.t()) ::
              {:ok, [Models.ResolveDocVariantModel.t()]} | {:error, any()}
      def resolve_doc_variant(doc_set_code, version) do
        Logger.debug("Calling stored procedure", procedure: "resolve_doc_variant")

        query(
          "select * from public.resolve_doc_variant($1, $2)",
          [doc_set_code, version]
        )
        |> Parsers.ResolveDocVariantParser.parse_result()
      end


      @doc """
      Calls database function public.search_documents
      """
      @spec search_documents(String.t(), map() | list(), map() | list(), integer()) ::
              {:ok, [Models.SearchDocumentsModel.t()]} | {:error, any()}
      def search_documents(correlation_id, search_criteria, search_settings, tenant_id) do
        Logger.debug("Calling stored procedure", procedure: "search_documents")

        query(
          "select * from public.search_documents($1, $2, $3, $4)",
          [correlation_id, search_criteria, search_settings, tenant_id]
        )
        |> Parsers.SearchDocumentsParser.parse_result()
      end


      @doc """
      Calls database function public.start_version_update
      """
      @spec start_version_update(String.t(), String.t(), String.t(), String.t()) ::
              {:ok, [Models.StartVersionUpdateModel.t()]} | {:error, any()}
      def start_version_update(version, title, description, component) do
        Logger.debug("Calling stored procedure", procedure: "start_version_update")

        query(
          "select * from public.start_version_update($1, $2, $3, $4)",
          [version, title, description, component]
        )
        |> Parsers.StartVersionUpdateParser.parse_result()
      end


      @doc """
      Calls database function public.stop_version_update
      """
      @spec stop_version_update(String.t(), String.t()) ::
              {:ok, [Models.StopVersionUpdateModel.t()]} | {:error, any()}
      def stop_version_update(version, component) do
        Logger.debug("Calling stored procedure", procedure: "stop_version_update")

        query(
          "select * from public.stop_version_update($1, $2)",
          [version, component]
        )
        |> Parsers.StopVersionUpdateParser.parse_result()
      end


      @doc """
      Calls database function auth.get_user_random_code
      """
      @spec auth_get_user_random_code() ::
              {:ok, [Models.AuthGetUserRandomCodeModel.t()]} | {:error, any()}
      def auth_get_user_random_code() do
        Logger.debug("Calling stored procedure", procedure: "get_user_random_code")

        query(
          "select * from auth.get_user_random_code()",
          []
        )
        |> Parsers.AuthGetUserRandomCodeParser.parse_result()
      end


    end
  end
end